FROM postgres:alpine
# ADD scripts/000001_init.up.sql /docker-entrypoint-initdb.d
# ADD scripts/000002_create_db.up.sql /docker-entrypoint-initdb.d
# ADD scripts/000003_give_permissions.up.sql /docker-entrypoint-initdb.d
# ADD scripts/000004_create_users_table.up.sql /docker-entrypoint-initdb.d
# ADD scripts/000005_create_wallets_table.up.sql /docker-entrypoint-initdb.d
# RUN chmod a+r /docker-entrypoint-initdb.d/*
EXPOSE 5432