// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   int64                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Iin                  string               `protobuf:"bytes,2,opt,name=Iin,proto3" json:"Iin,omitempty"`
	Login                string               `protobuf:"bytes,3,opt,name=Login,proto3" json:"Login,omitempty"`
	Role                 *Role                `protobuf:"bytes,4,opt,name=Role,proto3" json:"Role,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetIin() string {
	if m != nil {
		return m.Iin
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Role struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Wallet struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Number               int64    `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Iin                  string   `protobuf:"bytes,5,opt,name=Iin,proto3" json:"Iin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (m *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(m, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Wallet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Wallet) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Wallet) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Wallet) GetIin() string {
	if m != nil {
		return m.Iin
	}
	return ""
}

type WalletsList struct {
	Wallets              []*Wallet `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WalletsList) Reset()         { *m = WalletsList{} }
func (m *WalletsList) String() string { return proto.CompactTextString(m) }
func (*WalletsList) ProtoMessage()    {}
func (*WalletsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *WalletsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletsList.Unmarshal(m, b)
}
func (m *WalletsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletsList.Marshal(b, m, deterministic)
}
func (m *WalletsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletsList.Merge(m, src)
}
func (m *WalletsList) XXX_Size() int {
	return xxx_messageInfo_WalletsList.Size(m)
}
func (m *WalletsList) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletsList.DiscardUnknown(m)
}

var xxx_messageInfo_WalletsList proto.InternalMessageInfo

func (m *WalletsList) GetWallets() []*Wallet {
	if m != nil {
		return m.Wallets
	}
	return nil
}

type Iin struct {
	Iin                  string   `protobuf:"bytes,1,opt,name=iin,proto3" json:"iin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Iin) Reset()         { *m = Iin{} }
func (m *Iin) String() string { return proto.CompactTextString(m) }
func (*Iin) ProtoMessage()    {}
func (*Iin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *Iin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iin.Unmarshal(m, b)
}
func (m *Iin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iin.Marshal(b, m, deterministic)
}
func (m *Iin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iin.Merge(m, src)
}
func (m *Iin) XXX_Size() int {
	return xxx_messageInfo_Iin.Size(m)
}
func (m *Iin) XXX_DiscardUnknown() {
	xxx_messageInfo_Iin.DiscardUnknown(m)
}

var xxx_messageInfo_Iin proto.InternalMessageInfo

func (m *Iin) GetIin() string {
	if m != nil {
		return m.Iin
	}
	return ""
}

func init() {
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*AuthResponse)(nil), "auth.AuthResponse")
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Role)(nil), "auth.Role")
	proto.RegisterType((*Wallet)(nil), "auth.Wallet")
	proto.RegisterType((*WalletsList)(nil), "auth.WalletsList")
	proto.RegisterType((*Iin)(nil), "auth.Iin")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0xcb, 0xd3, 0x40,
	0x10, 0x25, 0x4d, 0xda, 0x92, 0xc9, 0x47, 0xd1, 0x45, 0x34, 0x04, 0xd4, 0x92, 0x83, 0x94, 0x82,
	0x29, 0x44, 0x04, 0xc1, 0x5e, 0x5a, 0x0f, 0x1a, 0xa8, 0x3d, 0xac, 0x55, 0xc1, 0xdb, 0xb6, 0x9d,
	0xa6, 0x8b, 0x49, 0x36, 0x64, 0x37, 0x8a, 0xff, 0xc4, 0x9f, 0x2b, 0xbb, 0x9b, 0xd5, 0x82, 0x97,
	0xef, 0x36, 0xef, 0xe5, 0xed, 0xcc, 0x9b, 0x79, 0x01, 0x60, 0xbd, 0xba, 0x66, 0x6d, 0x27, 0x94,
	0x20, 0x81, 0xae, 0x93, 0xe7, 0xa5, 0x10, 0x65, 0x85, 0x2b, 0xc3, 0x1d, 0xfb, 0xcb, 0x4a, 0xf1,
	0x1a, 0xa5, 0x62, 0x75, 0x6b, 0x65, 0xe9, 0x53, 0x18, 0x1f, 0xc4, 0x77, 0x6c, 0xc8, 0xa3, 0xa1,
	0x88, 0xbd, 0xb9, 0xb7, 0x08, 0xa9, 0x05, 0xe9, 0x07, 0xb8, 0xdb, 0xf4, 0xea, 0x4a, 0x51, 0xb6,
	0xa2, 0x91, 0x48, 0x62, 0x98, 0x7e, 0x44, 0x29, 0x59, 0x89, 0x83, 0xce, 0x41, 0xf2, 0x0c, 0x82,
	0x5e, 0x62, 0x17, 0x8f, 0xe6, 0xde, 0x22, 0xca, 0x21, 0x33, 0x56, 0x3e, 0x4b, 0xec, 0xa8, 0xe1,
	0xd3, 0xdf, 0x1e, 0x04, 0x1a, 0x92, 0x19, 0x8c, 0x8a, 0xb3, 0x79, 0xed, 0xd3, 0x51, 0x71, 0x26,
	0x0f, 0xc0, 0x2f, 0x78, 0x63, 0xde, 0x85, 0x54, 0x97, 0xda, 0xca, 0x4e, 0x94, 0xbc, 0x89, 0x7d,
	0x6b, 0xc5, 0x00, 0x3d, 0x80, 0x8a, 0x0a, 0xe3, 0xe0, 0x76, 0x80, 0x66, 0xa8, 0xe1, 0xc9, 0x1b,
	0x08, 0xdf, 0x75, 0xc8, 0x14, 0x9e, 0x37, 0x2a, 0x1e, 0x1b, 0x51, 0x92, 0xd9, 0xf5, 0x33, 0xb7,
	0x7e, 0x76, 0x70, 0xeb, 0xd3, 0x7f, 0xe2, 0x74, 0x69, 0x3b, 0xff, 0xe7, 0x8c, 0x40, 0xb0, 0x67,
	0x35, 0x0e, 0xd6, 0x4c, 0x9d, 0xb6, 0x30, 0xf9, 0xca, 0xaa, 0x0a, 0xd5, 0x7d, 0xd4, 0xe4, 0x31,
	0x4c, 0xf6, 0x7d, 0x7d, 0xc4, 0xce, 0xac, 0xe2, 0xd3, 0x01, 0xe9, 0x33, 0x6e, 0x59, 0xc5, 0x9a,
	0x93, 0x5d, 0xc7, 0xa3, 0x0e, 0xba, 0x6b, 0x8c, 0xff, 0x5e, 0x23, 0x7d, 0x0d, 0x91, 0x9d, 0x28,
	0x77, 0x5c, 0x2a, 0xf2, 0x02, 0xa6, 0x3f, 0x2d, 0x8c, 0xbd, 0xb9, 0xbf, 0x88, 0xf2, 0x3b, 0x7b,
	0x09, 0xab, 0xa1, 0xee, 0x63, 0xfa, 0xc4, 0x34, 0xd2, 0xfd, 0x38, 0x77, 0xa1, 0xea, 0x32, 0x5f,
	0x43, 0xa4, 0x23, 0xfd, 0x84, 0xdd, 0x0f, 0x7e, 0x42, 0xf2, 0x12, 0xe0, 0x0b, 0x76, 0xfc, 0xf2,
	0xcb, 0x84, 0x13, 0xd9, 0x66, 0x26, 0xfc, 0x84, 0x58, 0x70, 0xfb, 0x03, 0xe4, 0x6b, 0x98, 0x0d,
	0x6e, 0x5c, 0x83, 0x25, 0xc0, 0x7b, 0x54, 0x03, 0x49, 0x42, 0xfb, 0xa6, 0xe0, 0x4d, 0xf2, 0xf0,
	0xd6, 0x98, 0x31, 0xbf, 0x0d, 0xbf, 0x4d, 0xb3, 0xd5, 0x5b, 0x4d, 0x1f, 0x27, 0x26, 0x93, 0x57,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x49, 0x10, 0xc4, 0x37, 0xb4, 0x02, 0x00, 0x00,
}
